### ISSUE TITLE
Bootcamp Feedback TODO

### ISSUE THREAD

**Issue by danilolab** [laosarah/SAP011-movie-challenge-fw#5]
Deixo como sugestão os seguintes tópicos:

 - [ ] Aprofundar os estudos no Angular, quanto à modularização e componentização
 - [ ] Escrever os testes unitários
 - [ ] Estudar as bibliotecas RxJS e MomentJS
 - [ ] Criar projetos pessoais, com base em problemas reais e publicar no git para demonstrar seus conhecimentos, dicas de ideias: https://github.com/florinpop17/app-ideas?tab=readme-ov-file#tier-1-beginner-projects
 - [ ] Recomendação de sites: https://www.hackerrank.com/, https://leetcode.com/ e https://www.codewars.com/
